# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 31, 12, 42, 48, 521482)),
        ),
        migrations.AlterField(
            model_name='implementationquestionanswer',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 31, 12, 42, 48, 527740)),
        ),
        migrations.AlterField(
            model_name='interest',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 31, 12, 42, 48, 522477)),
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 31, 12, 42, 48, 526580)),
        ),
    ]
