# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-14 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_auto_20180531_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'verbose_name': 'Algorithm', 'verbose_name_plural': 'Algorithm'},
        ),
        migrations.AlterModelOptions(
            name='implementation',
            options={'verbose_name': 'Implementation', 'verbose_name_plural': 'Implementations'},
        ),
    ]
